apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: devops-catalog
  region: us-east-1
  version: "1.20"
managedNodeGroups:
- name: primary-1-20
  instanceType: t2.small
  minSize: 3
  maxSize: 6
  spot: true